#!/bin/bash

# Watchtower Build Script
# Packages the Agent and Manager plugins as WordPress-ready ZIP files

set -e  # Exit on error

echo "======================================"
echo "Watchtower Build"
echo "======================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Build directory
BUILD_DIR="$SCRIPT_DIR/build"

# Clean previous build
echo -e "${BLUE}Cleaning previous build...${NC}"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

# Get version from latest git tag
echo -e "${BLUE}Reading version from git tags...${NC}"
GIT_DESCRIBE=$(git describe --tags --match "v*.*.*" 2>/dev/null || echo "v0.0.1")

# Parse git describe output
# Format: v0.0.1 or v0.0.1-5-g1a2b3c4 (if commits exist after tag)
if [[ "$GIT_DESCRIBE" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+)-g([0-9a-f]+))?$ ]]; then
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
    MAINTENANCE="${BASH_REMATCH[3]}"
    COMMIT_COUNT="${BASH_REMATCH[5]}"
    COMMIT_HASH="${BASH_REMATCH[6]}"

    # If there are commits after the tag, append hash to maintenance
    if [[ -n "$COMMIT_HASH" ]]; then
        MAINTENANCE="${MAINTENANCE}-${COMMIT_HASH}"
        GIT_TAG="${MAJOR}.${MINOR}.${MAINTENANCE%%-*}"
        VERSION="${MAJOR}.${MINOR}.${MAINTENANCE}"
    else
        GIT_TAG="${GIT_DESCRIBE#v}"
        VERSION="$GIT_TAG"
    fi
else
    # Fallback
    MAJOR=0
    MINOR=0
    MAINTENANCE=1
    GIT_TAG="0.0.1"
    VERSION="0.0.1"
fi

# Generate version.properties in build directory
VERSION_FILE="$BUILD_DIR/version.properties"
cat > "$VERSION_FILE" << EOF
# Watchtower Version Information
# This file is automatically generated from git tags during the build process.
# Git describe: $GIT_DESCRIBE

major=$MAJOR
minor=$MINOR
maintenance=$MAINTENANCE
EOF

echo -e "${GREEN}Building version: ${VERSION}${NC}"
echo ""

# Build Agent Plugin
echo -e "${BLUE}Building Watchtower Agent plugin...${NC}"
AGENT_DIR="$BUILD_DIR/remote-agent"
mkdir -p "$AGENT_DIR"

# Copy agent files
cp -r remote-agent/* "$AGENT_DIR/"
cp "$VERSION_FILE" "$AGENT_DIR/"

# Remove development files
find "$AGENT_DIR" -name ".DS_Store" -delete
find "$AGENT_DIR" -name "*.swp" -delete
find "$AGENT_DIR" -name "*.swo" -delete
find "$AGENT_DIR" -name "*~" -delete

# Create ZIP
cd "$BUILD_DIR"
zip -r "watchtower-agent-${VERSION}.zip" remote-agent/ -q
echo -e "${GREEN}✓ Created: watchtower-agent-${VERSION}.zip${NC}"

# Build Manager Plugin
echo ""
echo -e "${BLUE}Building Watchtower Manager plugin...${NC}"
MANAGER_DIR="$BUILD_DIR/remote-manager"
mkdir -p "$MANAGER_DIR"

# Copy manager files
cp -r "$SCRIPT_DIR/remote-manager/"* "$MANAGER_DIR/"
cp "$VERSION_FILE" "$MANAGER_DIR/"

# Remove development files
find "$MANAGER_DIR" -name ".DS_Store" -delete
find "$MANAGER_DIR" -name "*.swp" -delete
find "$MANAGER_DIR" -name "*.swo" -delete
find "$MANAGER_DIR" -name "*~" -delete

# Create ZIP
zip -r "watchtower-manager-${VERSION}.zip" remote-manager/ -q
echo -e "${GREEN}✓ Created: watchtower-manager-${VERSION}.zip${NC}"

# Clean up temporary directories
cd "$SCRIPT_DIR"
rm -rf "$BUILD_DIR/remote-agent"
rm -rf "$BUILD_DIR/remote-manager"

# Summary
echo ""
echo "======================================"
echo -e "${GREEN}Build Complete!${NC}"
echo "======================================"
echo ""
echo "Artifacts created in build/:"
echo "  - watchtower-agent-${VERSION}.zip"
echo "  - watchtower-manager-${VERSION}.zip"
echo ""
echo "These ZIP files can be uploaded directly to WordPress"
echo "via Plugins → Add New → Upload Plugin"
echo ""
