@echo off
REM Watchtower Build Script for Windows
REM Packages the Agent and Manager plugins as WordPress-ready ZIP files

setlocal enabledelayedexpansion

echo ======================================
echo Watchtower Build
echo ======================================
echo.

REM Get script directory
set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%"

REM Build directory
set "BUILD_DIR=%SCRIPT_DIR%build"

REM Clean previous build
echo Cleaning previous build...
if exist "%BUILD_DIR%" rmdir /s /q "%BUILD_DIR%"
mkdir "%BUILD_DIR%"

REM Get version from latest git tag
echo Reading version from git tags...
for /f "delims=" %%i in ('git describe --tags --match "v*.*.*" 2^>nul') do set GIT_DESCRIBE=%%i
if not defined GIT_DESCRIBE set GIT_DESCRIBE=v0.0.1

REM Parse git describe output (v0.0.1 or v0.0.1-5-g1a2b3c4)
REM Check if there are commits after the tag (contains hyphen after version)
echo %GIT_DESCRIBE% | findstr /R "v[0-9]*\.[0-9]*\.[0-9]*-[0-9]*-g" >nul
if %ERRORLEVEL% EQU 0 (
    REM Format: v0.0.1-5-g1a2b3c4
    REM Extract base version and commit count
    for /f "tokens=1,2 delims=-" %%a in ("%GIT_DESCRIBE:v=%") do (
        set "BASE_VERSION=%%a"
        set "COMMIT_COUNT=%%b"
    )

    REM Parse base version
    for /f "tokens=1,2,3 delims=." %%a in ("!BASE_VERSION!") do (
        set MAJOR=%%a
        set MINOR=%%b
        set MAINTENANCE=%%c-!COMMIT_COUNT!
    )
    set "VERSION=!MAJOR!.!MINOR!.!MAINTENANCE!"
) else (
    REM Exact tag match - no commits after
    set VERSION=%GIT_DESCRIBE:v=%

    REM Parse version components
    for /f "tokens=1,2,3 delims=." %%a in ("%VERSION%") do (
        set MAJOR=%%a
        set MINOR=%%b
        set MAINTENANCE=%%c
    )
)

REM Check for uncommitted local changes
git status --porcelain 2>nul | findstr /R ".*" >nul
if %ERRORLEVEL% EQU 0 (
    echo Detected uncommitted changes, appending timestamp
    for /f "tokens=1-4 delims=/:. " %%a in ("%DATE% %TIME%") do (
        set "MONTH=%%b"
        set "DAY=%%c"
        set "HOUR=%%d"
        set "MINUTE=%%e"
    )
    REM Pad single digits with zero
    if "!MONTH:~1!"=="" set "MONTH=0!MONTH!"
    if "!DAY:~1!"=="" set "DAY=0!DAY!"
    if "!HOUR:~1!"=="" set "HOUR=0!HOUR!"
    if "!MINUTE:~1!"=="" set "MINUTE=0!MINUTE!"
    set "TIMESTAMP=!MONTH!!DAY!!HOUR!!MINUTE!"
    set "MAINTENANCE=!MAINTENANCE!-!TIMESTAMP!"
    set "VERSION=!MAJOR!.!MINOR!.!MAINTENANCE!"
)

REM Generate version.properties in build directory
set "VERSION_FILE=%BUILD_DIR%\version.properties"
(
    echo # Watchtower Version Information
    echo # This file is automatically generated from git tags during the build process.
    echo # Git describe: %GIT_DESCRIBE%
    echo.
    echo major=%MAJOR%
    echo minor=%MINOR%
    echo maintenance=%MAINTENANCE%
) > "%VERSION_FILE%"

echo Building version: %VERSION%
echo.

REM Build Agent Plugin
echo Building Watchtower Agent plugin...
set "AGENT_DIR=%BUILD_DIR%\remote-agent"
mkdir "%AGENT_DIR%"

REM Copy agent files
xcopy /E /I /Q "remote-agent\*" "%AGENT_DIR%\" > nul
copy /Y "%VERSION_FILE%" "%AGENT_DIR%\" > nul

REM Remove development files
del /S /Q "%AGENT_DIR%\.DS_Store" 2>nul
del /S /Q "%AGENT_DIR%\*.swp" 2>nul
del /S /Q "%AGENT_DIR%\*.swo" 2>nul
del /S /Q "%AGENT_DIR%\*~" 2>nul

REM Create ZIP (requires PowerShell)
cd /d "%BUILD_DIR%"
powershell -Command "Compress-Archive -Path 'remote-agent' -DestinationPath 'watchtower-agent-%VERSION%.zip' -Force"
echo [32m✓ Created: watchtower-agent-%VERSION%.zip[0m

REM Build Manager Plugin
echo.
echo Building Watchtower Manager plugin...
set "MANAGER_DIR=%BUILD_DIR%\remote-manager"
mkdir "%MANAGER_DIR%"

REM Copy manager files
xcopy /E /I /Q "%SCRIPT_DIR%remote-manager\*" "%MANAGER_DIR%\" > nul
copy /Y "%VERSION_FILE%" "%MANAGER_DIR%\" > nul

REM Remove development files
del /S /Q "%MANAGER_DIR%\.DS_Store" 2>nul
del /S /Q "%MANAGER_DIR%\*.swp" 2>nul
del /S /Q "%MANAGER_DIR%\*.swo" 2>nul
del /S /Q "%MANAGER_DIR%\*~" 2>nul

REM Create ZIP
powershell -Command "Compress-Archive -Path 'remote-manager' -DestinationPath 'watchtower-manager-%VERSION%.zip' -Force"
echo [32m✓ Created: watchtower-manager-%VERSION%.zip[0m

REM Clean up temporary directories
cd /d "%SCRIPT_DIR%"
rmdir /s /q "%BUILD_DIR%\remote-agent"
rmdir /s /q "%BUILD_DIR%\remote-manager"

REM Summary
echo.
echo ======================================
echo Build Complete!
echo ======================================
echo.
echo Artifacts created in build/:
echo   - watchtower-agent-%VERSION%.zip
echo   - watchtower-manager-%VERSION%.zip
echo.
echo These ZIP files can be uploaded directly to WordPress
echo via Plugins -^> Add New -^> Upload Plugin
echo.

endlocal
pause
