name=Watchtower
description=Central management plugin to control and monitor multiple Watchtower Agent installations across WordPress sites

author=Brayall, LLC
author-uri=https://github.com/abrayall
plugin-uri=https://github.com/abrayall/watchtower
license=GPL v2 or later
license-uri=https://www.gnu.org/licenses/gpl-2.0.html

main=manager.php
include=assets,includes
text-domain=watchtower-manager

requires=5.8
requires-php=7.4
