name=Watchtower Agent
description=Remote management agent that provides REST API endpoints for WordPress management including user management, backups, and updates. Designed to be controlled by Watchtower Manager.

author=Brayall, LLC
author-uri=https://github.com/abrayall
plugin-uri=https://github.com/abrayall/watchtower
license=GPL v2 or later
license-uri=https://www.gnu.org/licenses/gpl-2.0.html

main=agent.php
include=includes
text-domain=watchtower-agent

requires=5.8
requires-php=7.4
